# frozen_string_literal: true

module Yamshik
  # A shipment (отправление) — the central entity of the domain model.
  #
  # +reference+ is the idempotency anchor and is always generated by
  # the client of the gem.
  Parcel = Data.define(:reference, :external_id, :carrier, :registration_state,
                       :sender, :recipient, :origin, :destination,
                       :items, :places, :services, :comment) do
    # Registration lifecycle states (async registration, DESIGN.md §4).
    const_set(:REGISTRATION_STATES, %i[pending registered rejected].freeze)

    # @!attribute [r] reference
    #   @return [String] client-generated idempotency anchor
    # @!attribute [r] external_id
    #   @return [String, nil] carrier-side id, nil until creation
    # @!attribute [r] carrier
    #   @return [Symbol, nil] carrier key, set by the adapter
    # @!attribute [r] registration_state
    #   @return [Symbol] one of {REGISTRATION_STATES}
    # @!attribute [r] sender
    #   @return [Contact] sender
    # @!attribute [r] recipient
    #   @return [Contact] recipient
    # @!attribute [r] origin
    #   @return [Point] origin
    # @!attribute [r] destination
    #   @return [Point] destination
    # @!attribute [r] items
    #   @return [Array<Item>] declared contents
    # @!attribute [r] places
    #   @return [Array<Place>] cargo places
    # @!attribute [r] services
    #   @return [Array<ParcelService>] additional services
    # @!attribute [r] comment
    #   @return [String, nil] free-form comment

    # @param reference [String] client-generated idempotency anchor
    # @param sender [Contact] sender
    # @param recipient [Contact] recipient
    # @param origin [Point] origin
    # @param destination [Point] destination
    # @param external_id [String, nil] carrier-side id
    # @param carrier [Symbol, nil] carrier key, set by the adapter
    # @param registration_state [Symbol] one of {REGISTRATION_STATES}
    # @param items [Array<Item>] declared contents
    # @param places [Array<Place>] cargo places
    # @param services [Array<ParcelService>] additional services
    # @param comment [String, nil] free-form comment
    # @raise [ArgumentError] on missing required attributes, unknown
    #   registration_state or inconsistent item allocation across places
    def initialize(reference:, sender:, recipient:, origin:, destination:,
                   external_id: nil, carrier: nil, registration_state: :pending,
                   items: [], places: [], services: [], comment: nil)
      validate_present!(reference:, sender:, recipient:, origin:, destination:)
      validate_registration_state!(registration_state)
      validate_place_items!(items, places)

      super(reference:, sender:, recipient:, origin:, destination:,
            external_id:, carrier:, registration_state:, comment:,
            items: items.freeze, places: places.freeze, services: services.freeze)
    end

    # Delivery mode at the last mile, derived from the destination point.
    #
    # @return [Symbol] :door or :pickup_point
    def delivery_type
      destination.type
    end

    private

    def validate_present!(attributes)
      attributes.each do |name, value|
        raise ArgumentError, "#{name} is required" if value.nil?
      end
    end

    def validate_registration_state!(registration_state)
      return if self.class::REGISTRATION_STATES.include?(registration_state)

      raise ArgumentError,
            "registration_state must be one of #{self.class::REGISTRATION_STATES.inspect}, " \
            "got #{registration_state.inspect}"
    end

    # The core guarantees: for every item, the total quantity allocated
    # across all places does not exceed the item's declared quantity.
    def validate_place_items!(items, places)
      allocated_totals(places).each do |item, total|
        validate_known_item!(items, item)
        validate_allocated_quantity!(item, total)
      end
    end

    def allocated_totals(places)
      totals = Hash.new(0)
      places.each do |place|
        place.place_items.each { |place_item| totals[place_item.item] += place_item.quantity }
      end
      totals
    end

    def validate_known_item!(items, item)
      return if items.include?(item)

      raise ArgumentError, "place_items reference an item that is not in the parcel's items: #{item.name.inspect}"
    end

    def validate_allocated_quantity!(item, total)
      return if total <= item.quantity

      raise ArgumentError,
            "allocated quantity (#{total}) of item #{item.name.inspect} exceeds declared quantity (#{item.quantity})"
    end
  end
end
