# frozen_string_literal: true

module Yamshik
  # A shipment (отправление) — the central entity of the domain model.
  #
  # +reference+ is the idempotency anchor and is always generated by
  # the client of the gem.
  class Parcel
    # Registration lifecycle states (async registration, DESIGN.md §4).
    REGISTRATION_STATES = %i[pending registered rejected].freeze

    # @return [String] client-generated idempotency anchor
    attr_reader :reference
    # @return [String, nil] carrier-side id, nil until creation
    attr_reader :external_id
    # @return [Symbol, nil] carrier key, set by the adapter
    attr_reader :carrier
    # @return [Symbol] one of {REGISTRATION_STATES}
    attr_reader :registration_state
    # @return [Contact] sender
    attr_reader :sender
    # @return [Contact] recipient
    attr_reader :recipient
    # @return [Point] origin
    attr_reader :origin
    # @return [Point] destination
    attr_reader :destination
    # @return [Array<Item>] declared contents
    attr_reader :items
    # @return [Array<Place>] cargo places
    attr_reader :places
    # @return [Array<ParcelService>] additional services
    attr_reader :services
    # @return [String, nil] free-form comment
    attr_reader :comment

    # @param reference [String] client-generated idempotency anchor
    # @param sender [Contact] sender
    # @param recipient [Contact] recipient
    # @param origin [Point] origin
    # @param destination [Point] destination
    # @param external_id [String, nil] carrier-side id
    # @param carrier [Symbol, nil] carrier key, set by the adapter
    # @param registration_state [Symbol] one of {REGISTRATION_STATES}
    # @param items [Array<Item>] declared contents
    # @param places [Array<Place>] cargo places
    # @param services [Array<ParcelService>] additional services
    # @param comment [String, nil] free-form comment
    # @raise [ArgumentError] on missing required attributes, unknown
    #   registration_state or inconsistent item allocation across places
    def initialize(reference:, sender:, recipient:, origin:, destination:,
                   external_id: nil, carrier: nil, registration_state: :pending,
                   items: [], places: [], services: [], comment: nil)
      @reference = reference
      @external_id = external_id
      @carrier = carrier
      @registration_state = registration_state
      @sender = sender
      @recipient = recipient
      @origin = origin
      @destination = destination
      @items = items.freeze
      @places = places.freeze
      @services = services.freeze
      @comment = comment
      validate!
      freeze
    end

    # Delivery mode at the last mile, derived from the destination point.
    #
    # @return [Symbol] :door or :pickup_point
    def delivery_type
      destination.type
    end

    private

    def validate!
      validate_present!
      validate_registration_state!
      validate_place_items!
    end

    def validate_present!
      %i[reference sender recipient origin destination].each do |name|
        raise ArgumentError, "#{name} is required" if public_send(name).nil?
      end
    end

    def validate_registration_state!
      return if REGISTRATION_STATES.include?(registration_state)

      raise ArgumentError,
            "registration_state must be one of #{REGISTRATION_STATES.inspect}, got #{registration_state.inspect}"
    end

    # The core guarantees: for every item, the total quantity allocated
    # across all places does not exceed the item's declared quantity.
    def validate_place_items!
      allocated_totals.each do |item, total|
        validate_known_item!(item)
        validate_allocated_quantity!(item, total)
      end
    end

    def allocated_totals
      totals = Hash.new(0)
      places.each do |place|
        place.place_items.each { |place_item| totals[place_item.item] += place_item.quantity }
      end
      totals
    end

    def validate_known_item!(item)
      return if items.include?(item)

      raise ArgumentError, "place_items reference an item that is not in the parcel's items: #{item.name.inspect}"
    end

    def validate_allocated_quantity!(item, total)
      return if total <= item.quantity

      raise ArgumentError,
            "allocated quantity (#{total}) of item #{item.name.inspect} exceeds declared quantity (#{item.quantity})"
    end
  end
end
